#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

# Make sure all the user-generated data directories exist

dirs=(fullsize,original,square_thumbnails,theme_uploads,thumbnails)

for f in "${dirs[@]}"; do
  mkdir -p $OPENSHIFT_DATA_DIR/$f
  ln -snf $OPENSHIFT_DATA_DIR/$f $OPENSHIFT_REPO_DIR/php/files
done

